project_name: go-tooling-portal

dist: ./dist

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - id: release-build
    binary: go-tooling-portal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/sfarosu/{{ .ProjectName }}/cmd/version.BuildDate={{.Date}}'
      - -X 'github.com/sfarosu/{{ .ProjectName }}/cmd/version.GitShortHash={{.ShortCommit}}'

archives:
  - id: release-archive
    builds:
      - release-build
    format: tar.gz
    files:
      - build
      - web

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "SNAPSHOT-{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  ids:
    - release-archive
  github:
    owner: sfarosu
    name: go-tooling-portal

# If running on Debian, make sure `qemu-user-static` package is installed; needed by docker to build against arm64 arch
dockers:
  - dockerfile: Dockerfile-Goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/sfarosu/{{ .ProjectName }}:latest-amd64"
      - "docker.io/sfarosu/{{ .ProjectName }}:{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - scripts

  - dockerfile: Dockerfile-Goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "docker.io/sfarosu/{{ .ProjectName }}:latest-arm64"
      - "docker.io/sfarosu/{{ .ProjectName }}:{{ .Version }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
      - scripts

docker_manifests:
- name_template: "docker.io/sfarosu/{{ .ProjectName }}:latest"
  image_templates:
    - "docker.io/sfarosu/{{ .ProjectName }}:latest-amd64"
    - "docker.io/sfarosu/{{ .ProjectName }}:latest-arm64"
- name_template: "docker.io/sfarosu/{{ .ProjectName }}:{{ .Version }}"
  image_templates:
    - "docker.io/sfarosu/{{ .ProjectName }}:{{ .Version }}-amd64"
    - "docker.io/sfarosu/{{ .ProjectName }}:{{ .Version }}-arm64"
