apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-tooling-portal
  labels:
    app: go-tooling-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-tooling-portal
  template:
    metadata:
      labels:
        app: go-tooling-portal
    spec:
      containers:
      - name: go-tooling-portal
        image: sfarosu/go-tooling-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1"
