apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-tooling-portal
  name: go-tooling-portal
spec:
  ports:
  - name: 8100-tcp
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: go-tooling-portal
  sessionAffinity: None
  type: ClusterIP
